---

jobs:
  - name: build
    serial: true
    plan:
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: [ building..., OK! ]

  - name: test
    serial: true
    plan:
      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: [ testing..., OK! ]

  - name: ship
    serial: true
    plan:
      - task: ship
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: [ shipping..., OK! ]
