---

jobs:
  - name: build
    serial: true
    plan:
      - in_parallel:
          - get: git
            trigger: true
          - get: ci-image

      - task: build
        image: ci-image
        config:
          platform: linux
          outputs:
            - name: build-metadata
          run:
            path: sh
            args:
              - -ec
              - |
                echo Building...
                sleep 5
                echo "my-precious-build" > build-metadata/build-family
                echo "OK!"

      - put: build-metadata
        params:
          directory: build-metadata
          overrides:
            build-family-plip: my-precious-build-plop

  - name: test
    serial: true
    plan:
      - in_parallel:
          - get: git
            passed: [ build ]
            trigger: true
          - get: ci-image
            passed: [ build ]

      - task: test
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Testing...
                sleep 5
                echo "OK!"

  - name: ship
    serial: true
    plan:
      - in_parallel:
          - get: git
            passed: [ test ]
            trigger: true
          - get: ci-image
            passed: [ test ]
          - get: build-metadata
            passed: [ build ]

      - task: ship
        image: ci-image
        config:
          platform: linux
          inputs:
            - name: build-metadata
          run:
            path: sh
            args:
              - -ec
              - |
                echo Shipping...
                cat build-metadata/build-family
                sleep 5
                echo "OK!"

resources:
  - name: build-metadata
    type: key-value
    icon: database-outline

  - name: git
    type: git
    icon: github
    source:
      uri: https://github.com/gstackio/yasak.git

  - name: ci-image
    type: registry-image
    icon: docker
    source: { repository: busybox }


resource_types:

  - name: key-value
    type: registry-image
    source:
      repository: gstack/keyval-resource
