---

groups:
  - name: build
    jobs:
      - build
      - test
      - ship-to-integration
  - name: integration
    jobs:
      - deploy-integration
      - integration-tests
      - ship-to-prod
  - name: prod
    jobs:
      - deploy-prod
      - smoke-tests

jobs:
  - name: build
    serial: true
    plan:
      - in_parallel:
          - get: git
            trigger: true
          - get: ci-image
          - get: common-tasks

      - task: build
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Building...
                sleep 5
                echo "OK!"

      - task: echo-to-file
        file: common-tasks/echo-to-file/task.yml
        params:
          MESSAGE: build-family=my-precious-build
          FILENAME: keyval.properties
        output_mapping:
          output: build-metadata

      - put: build-metadata
        params:
          file: build-metadata/keyval.properties

  - name: test
    serial: true
    plan:
      - in_parallel:
          - get: git
            passed: [ build ]
            trigger: true
          - get: ci-image
            passed: [ build ]

      - task: test
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Testing...
                sleep 5
                echo "OK!"

  - name: ship-to-integration
    old_name: ship
    serial: true
    plan:
      - in_parallel:
          - get: git
            passed: [ test ]
            trigger: true
          - get: ci-image
            passed: [ test ]
          - get: build-metadata
            passed: [ build ]

      - task: ship
        image: ci-image
        config:
          platform: linux
          inputs:
            - name: build-metadata
          run:
            path: sh
            args:
              - -ec
              - |
                echo Shipping...
                grep "^build-family=" build-metadata/keyval.properties
                sleep 5
                echo "OK!"

      - put: integration
        params:
          repository: git

  - name: deploy-integration
    serial: true
    plan:
      - in_parallel:
          - get: integration
            passed: [ ship-to-integration ]
            trigger: true
          - get: ci-image
            passed: [ ship-to-integration ]

      - task: deploy-integration
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Deploying...
                sleep 5
                echo "OK!"

  - name: integration-tests
    serial: true
    plan:
      - in_parallel:
          - get: integration
            passed: [ deploy-integration ]
            trigger: true
          - get: ci-image
            passed: [ deploy-integration ]

      - task: integration-tests
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Testing...
                sleep 5
                echo "OK!"

  - name: ship-to-prod
    old_name: ship
    serial: true
    plan:
      - in_parallel:
          - get: integration
            passed: [ integration-tests ]
            trigger: true
          - get: ci-image
            passed: [ integration-tests ]

      - task: ship-to-prod
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Shipping...
                sleep 5
                echo "OK!"

      - put: prod
        params:
          repository: integration

  - name: deploy-prod
    serial: true
    plan:
      - in_parallel:
          - get: prod
            passed: [ ship-to-prod ]
            trigger: true
          - get: ci-image
            passed: [ ship-to-prod ]

      - task: deploy-prod
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Deploying...
                sleep 5
                echo "OK!"

  - name: smoke-tests
    serial: true
    plan:
      - in_parallel:
          - get: prod
            passed: [ deploy-prod ]
            trigger: true
          - get: ci-image
            passed: [ deploy-prod ]

      - task: smoke-tests
        image: ci-image
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                echo Running smoke tests...
                sleep 5
                echo "OK!"



resources:

  - name: common-tasks
    type: git
    icon: github
    source:
      uri: https://github.com/EngineerBetter/concourse-tasks.git

  - name: build-metadata
    type: key-value
    icon: database-outline

  - name: git
    type: git
    icon: github
    source:
      uri: https://github.com/gstackio/concourse-training-dummy.git
    check_every: 24h
    webhook_token: ((concourse-webhook-token))

  - name: integration
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/concourse-training-dummy.git
      branch: integration
      private_key: ((github-private-key))

  - name: prod
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/concourse-training-dummy.git
      branch: prod
      private_key: ((github-private-key))

  - name: ci-image
    type: registry-image
    icon: docker
    source: { repository: busybox }


resource_types:

  - name: key-value
    type: registry-image
    source:
      repository: swce/keyval-resource
